"""initial schema (Phase 2)

Revision ID: 0001
Revises:
Create Date: 2026-10-08 14:45:50.028516
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "append_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file", sa.String(length=32), nullable=False),
        sa.Column("row_key", sa.String(length=40), nullable=False),
        sa.Column("line_sha256", sa.String(length=64), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("appended_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file", "row_key"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=40), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)

    op.create_table(
        "breaches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("discovered_at", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_json", sa.Text(), nullable=False),
        sa.Column("ec_notified_at", sa.String(length=32), nullable=True),
        sa.Column("statutory_notes", sa.Text(), nullable=False),
        sa.Column("closed_at", sa.String(length=32), nullable=True),
        sa.Column("releases_paused", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ethics_approval",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("committee_name", sa.String(length=200), nullable=False),
        sa.Column("approval_ref", sa.String(length=80), nullable=False),
        sa.Column("protocol_version", sa.String(length=40), nullable=False),
        sa.Column("approval_date", sa.String(length=10), nullable=False),
        sa.Column("expiry_date", sa.String(length=10), nullable=False),
        sa.Column("archive_start", sa.String(length=10), nullable=False),
        sa.Column("waiver_cutoff", sa.String(length=10), nullable=False),
        sa.Column("cohort_cap", sa.Integer(), nullable=False),
        sa.Column("cap_unit", sa.String(length=8), nullable=False),
        sa.Column("notice_start", sa.String(length=10), nullable=False),
        sa.Column("optout_window_days", sa.Integer(), nullable=False),
        sa.Column("legal_opinion", sa.Boolean(), nullable=False),
        sa.Column("legal_opinion_date", sa.String(length=10), nullable=True),
        sa.Column("ec_amendment_refs_json", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=False),
        sa.CheckConstraint("cap_unit IN ('images', 'studies')", name="ck_cap_unit"),
        sa.CheckConstraint("cohort_cap >= 0", name="ck_cohort_cap"),
        sa.CheckConstraint("optout_window_days BETWEEN 60 AND 90", name="ck_optout_window"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ethics_approval", schema=None) as batch_op:
        batch_op.create_index(
            "ux_ethics_one_active", ["active"], unique=True, sqlite_where=sa.text("active = 1")
        )

    op.create_table(
        "exclusions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("study_key", sa.String(length=64), nullable=False),
        sa.Column("source_name_hash", sa.String(length=64), nullable=False),
        sa.Column("patient_code", sa.String(length=13), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("rule_id", sa.String(length=40), nullable=False),
        sa.Column("rules_version", sa.String(length=20), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exclusions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exclusions_job_id"), ["job_id"], unique=False)

    op.create_table(
        "licensees",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("dac_approval_ref", sa.String(length=80), nullable=True),
        sa.Column("dac_approval_date", sa.String(length=10), nullable=True),
        sa.Column("ec_notified_date", sa.String(length=10), nullable=True),
        sa.Column("licence_ref", sa.String(length=80), nullable=True),
        sa.Column("licence_start", sa.String(length=10), nullable=True),
        sa.Column("licence_expiry", sa.String(length=10), nullable=True),
        sa.Column("confidentiality_date", sa.String(length=10), nullable=True),
        sa.Column("deletion_certificate_date", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "list_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("list_type", sa.String(length=20), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("matched", sa.Integer(), nullable=False),
        sa.Column("importer_id", sa.String(length=40), nullable=False),
        sa.Column("imported_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "records",
        sa.Column("record_id", sa.String(length=13), nullable=False),
        sa.Column("patient_code", sa.String(length=13), nullable=False),
        sa.Column("study_key", sa.String(length=64), nullable=False),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.Column("finalised_version", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("record_id"),
        sa.UniqueConstraint("study_key"),
    )
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_records_patient_code"), ["patient_code"], unique=False)

    op.create_table(
        "source_files",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("record_id", sa.String(length=13), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sop_key", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("seen_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("sha256"),
    )
    with op.batch_alter_table("source_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_files_record_id"), ["record_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_files_sop_key"), ["sop_key"], unique=False)

    op.create_table(
        "images",
        sa.Column("image_id", sa.String(length=32), nullable=False),
        sa.Column("record_id", sa.String(length=13), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("row_json", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.record_id"],
        ),
        sa.PrimaryKeyConstraint("image_id"),
    )
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.create_index("ix_images_record_version", ["record_id", "version"], unique=False)

    op.create_table(
        "patient_flags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patient_code", sa.String(length=13), nullable=False),
        sa.Column("flag_type", sa.String(length=20), nullable=False),
        sa.Column("list_version_id", sa.Integer(), nullable=False),
        sa.Column("consent_value", sa.String(length=3), nullable=True),
        sa.Column("consent_date", sa.String(length=10), nullable=True),
        sa.Column("added_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_version_id"],
            ["list_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patient_flags", schema=None) as batch_op:
        batch_op.create_index("ix_flags_patient_type", ["patient_code", "flag_type"], unique=False)

    op.create_table(
        "record_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("record_id", sa.String(length=13), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("row_json", sa.Text(), nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("review_flags_json", sa.Text(), nullable=False),
        sa.Column("findings_json", sa.Text(), nullable=False),
        sa.Column("hold_reason", sa.String(length=120), nullable=True),
        sa.Column("finding_category", sa.String(length=40), nullable=True),
        sa.Column("reviewer_id", sa.String(length=40), nullable=True),
        sa.Column("decided_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("finalised_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.record_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", "version"),
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("licensee_id", sa.String(length=40), nullable=False),
        sa.Column("export_type", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column("gate_report_json", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["licensee_id"],
            ["licensees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "withdrawals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("record_id", sa.String(length=13), nullable=False),
        sa.Column("patient_code", sa.String(length=13), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("list_version_id", sa.Integer(), nullable=False),
        sa.Column("withdrawn_at", sa.String(length=32), nullable=False),
        sa.Column("row_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["list_version_id"],
            ["list_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.record_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id"),
    )
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_withdrawals_patient_code"), ["patient_code"], unique=False)

    op.create_table(
        "reid_tests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("modality", sa.String(length=4), nullable=False),
        sa.Column("release_id", sa.String(length=40), nullable=True),
        sa.Column("tester", sa.String(length=200), nullable=False),
        sa.Column("tested_on", sa.String(length=10), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("cases_attempted", sa.Integer(), nullable=False),
        sa.Column("cases_reidentified", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("recorded_by", sa.String(length=40), nullable=False),
        sa.Column("recorded_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "release_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("release_id", sa.String(length=40), nullable=False),
        sa.Column("record_id", sa.String(length=13), nullable=False),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.record_id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("release_id", "record_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_records")
    op.drop_table("reid_tests")
    with op.batch_alter_table("withdrawals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_withdrawals_patient_code"))

    op.drop_table("withdrawals")
    op.drop_table("releases")
    op.drop_table("record_versions")
    with op.batch_alter_table("patient_flags", schema=None) as batch_op:
        batch_op.drop_index("ix_flags_patient_type")

    op.drop_table("patient_flags")
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_index("ix_images_record_version")

    op.drop_table("images")
    with op.batch_alter_table("source_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_files_sop_key"))
        batch_op.drop_index(batch_op.f("ix_source_files_record_id"))

    op.drop_table("source_files")
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_records_patient_code"))

    op.drop_table("records")
    op.drop_table("list_versions")
    op.drop_table("licensees")
    with op.batch_alter_table("exclusions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exclusions_job_id"))

    op.drop_table("exclusions")
    with op.batch_alter_table("ethics_approval", schema=None) as batch_op:
        batch_op.drop_index("ux_ethics_one_active", sqlite_where=sa.text("active = 1"))

    op.drop_table("ethics_approval")
    op.drop_table("breaches")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    op.drop_table("append_log")
    # ### end Alembic commands ###
