"""No identifying data in logs (SPEC §7, CLAUDE.md rule 2). TR-SEC-02.

``install()`` wraps the logging record factory, so every record from any logger (the app, uvicorn,
libraries) is checked once, before any handler sees it. A record whose message or traceback matches an
identifier pattern is replaced by a fixed notice that names only the pattern kind; the text is dropped.

The patterns are the report redaction rules (phone, 12-digit ID, ABHA, PAN, email, UHID/MRN and
registration numbers, titled names) plus labelled fields, absolute file paths and non-standard DICOM UIDs.
Limit: a bare surname with no title or label cannot be recognised by a pattern; the rule that logs carry
record_id / job_id / counts only remains the main defence.
"""

from __future__ import annotations

import logging
import re
import traceback
from collections.abc import Callable
from typing import Any

from app.deid.report.redact import REGEX_RULES

SUPPRESSED = "[log message suppressed: possible identifier ({kind})]"

_KINDS = ("EMAIL", "PHONE", "ID12", "ABHA", "PAN", "REGNO", "MRN", "NAME")
_EXTRA: list[tuple[str, re.Pattern[str]]] = [
    (
        "LABEL",
        re.compile(
            r"(?i)\b(?:patient\s*name|pt\.?\s*name|patient\s*id|uhid|mrn|d\.?o\.?b\.?|date\s*of\s*birth|"
            r"address|mobile|phone|aadhaa?r)\s*[:=]\s*\S"
        ),
    ),
    # absolute paths: Windows drive or UNC, and the usual macOS/Linux data locations (not URL paths)
    ("PATH", re.compile(r"(?i)(?<![\w/])(?:[a-z]:[\\/]|\\\\[\w.$-]+\\)")),
    ("PATH", re.compile(r"(?<![\w.])/(?:Users|home|Volumes|mnt|media|private|tmp|var/folders)/")),
    # a DICOM UID that is neither standard (1.2.840.10008.) nor generated by this app (2.25.)
    ("UID", re.compile(r"(?<![\d.])(?!1\.2\.840\.10008\.)(?!2\.25\.)[012](?:\.\d+){4,}")),
]
PATTERNS: list[tuple[str, re.Pattern[str]]] = [(k, p) for k, p in REGEX_RULES if k in _KINDS] + _EXTRA

_installed: dict[str, Callable[..., logging.LogRecord]] = {}


def find_identifier(text: str) -> str | None:
    """The kind of the first identifier pattern found in ``text``, or None."""
    for kind, pattern in PATTERNS:
        if pattern.search(text):
            return kind
    return None


def _record_text(record: logging.LogRecord) -> str:
    try:
        text = record.getMessage()
    except Exception:  # noqa: BLE001 - a bad format string must not crash logging
        text = str(record.msg)
    if record.exc_info and record.exc_info[1] is not None:
        text += "\n" + "".join(traceback.format_exception(*record.exc_info))
    if record.stack_info:
        text += "\n" + record.stack_info
    return text


def sanitise(record: logging.LogRecord) -> logging.LogRecord:
    kind = find_identifier(_record_text(record))
    if kind is not None:
        record.msg, record.args = SUPPRESSED.format(kind=kind), None
        record.exc_info, record.exc_text, record.stack_info = None, None, None
    return record


class PhiLogFilter(logging.Filter):
    """The same check as a handler filter (for handlers built outside this process's factory)."""

    def filter(self, record: logging.LogRecord) -> bool:
        sanitise(record)
        return True


def install() -> None:
    """Idempotent: wrap the current log record factory once."""
    if "factory" in _installed:
        return
    previous = logging.getLogRecordFactory()

    def factory(*args: Any, **kwargs: Any) -> logging.LogRecord:
        return sanitise(previous(*args, **kwargs))

    _installed["factory"] = previous
    logging.setLogRecordFactory(factory)


def uninstall() -> None:
    previous = _installed.pop("factory", None)
    if previous is not None:
        logging.setLogRecordFactory(previous)
